language: go
go:
  - 1.5
  - 1.6
  - release
  - tip

script:
  # install dependencies
  - ./scripts/setup.sh

  # build core and plugin binaries
  - ./scripts/dev.sh all
    
  # test packages
  - ./scripts/test.sh core
  - ./scripts/test.sh internal
  - ./scripts/test.sh plugin/loadbalancer
  - ./scripts/test.sh plugin/modifier
  - ./scripts/test.sh plugin/metric
  - ./scripts/test.sh plugin/upstream
  - ./scripts/test.sh plugin/router

  # plugin tests
  - ./scripts/test.sh plugins/consul-loadbalancer
  - ./scripts/test.sh plugins/docker-upstreams
  - ./scripts/test.sh plugins/dogstatsd-metrics
  - ./scripts/test.sh plugins/local-api-upstreams
  - ./scripts/test.sh plugins/local-metrics
  - ./scripts/test.sh plugins/modifier
